#5
from tkinter import*

root=Tk()

root.title('tk')
label_0=Label(root, text='Movie Booking id')
label_0.grid(row=0)
entry_0=Entry(root)
entry_0.grid(row=0,column=1)
label_1=Label(root, text='Person Name :')
label_1.grid(row=1)
entry_1=Entry(root)
entry_1.grid(row=1,column=1)
label_2=Label(root, text='Movie Name')
label_2.grid(row=2)
entry_2=Entry(root)
entry_2.insert(0,'Avengers')
entry_2.grid(row=2,column=1)
label_3=Label(root, text='Class')
label_3.grid(row=3)
var_0=IntVar()
radio_0=Radiobutton(root, text='A', value=1, variable=var_0)
radio_0.grid(row=3,column=1)
radio_1=Radiobutton(root, text='B', value=2, variable=var_0)
radio_1.grid(row=3,column=2)
label_4=Label(root, text='Time of show')
label_4.grid(row=3, column=3)
check_0=Checkbutton(root, text='7.15 pm')
check_0.grid(row=3,column=4)
check_1=Checkbutton(root, text='9 am')
check_1.grid(row=3, column=5)
label_5=Label(root, text='Number of Tickets')
label_5.grid(row=4)
scale_0=Scale(root, from_=3, to=10,orient=HORIZONTAL)
scale_0.grid(row=4, column=1)
bt_0=Button(root, text="Insert")
bt_0.grid(row=5)
bt_1=Button(root, text="Update")
bt_1.grid(row=5,column=1)
bt_2=Button(root, text="Delete")
bt_2.grid(row=6)
bt_3=Button(root, text="Select")
bt_3.grid(row=6,column=1)

root.mainloop()

