#1
from tkinter import*

root=Tk()

#root.geometry('250x170')
root.title('tk')
label_0=Label(root, text='Regno')
label_0.grid(row=0)
entry_0=Entry(root)
entry_0.grid(row=0,column=2)
label_1=Label(root, text='Name:')
label_1.grid(row=1)
entry_1=Entry(root)
entry_1.grid(row=1,column=2)
label_2=Label(root, text='Dept')
label_2.grid(row=2)
entry_2=Entry(root)
entry_2.insert(0,'CSE')
entry_2.grid(row=2,column=2)
label_2=Label(root, text='Gender')
label_2.grid(row=3)
var_0=IntVar()
radio_0=Radiobutton(root, text='Male',value=1,variable=var_0)
radio_0.grid(row=3,column=2)
radio_1=Radiobutton(root, text='Female',value=2,variable=var_0)
radio_1.grid(row=3,column=3)
radio_1.deselect()
label_3=Label(root,text='Age')
label_3.grid(row=4)
var_1=DoubleVar(value=19)
spin_0=Spinbox(root,from_=0, to=100, textvariable=var_1)
spin_0.grid(row=4, column=2)
bt_0=Button(root, text="Insert")
bt_0.grid(row=5)
bt_1=Button(root, text="Update")
bt_1.grid(row=5,column=2)
bt_2=Button(root, text="Delete")
bt_2.grid(row=6)
bt_3=Button(root, text="Select")
bt_3.grid(row=6,column=2)

root.mainloop()