from tkinter import *
from tkinter import messagebox
from tkinter import ttk
master = Tk()
master.title('tk')
Label(master,text='CAR RENTAL RECEIPT').grid(row=0,column=2)
Label(master, text='Date').grid(row=2)
Label(master,text='Receipt#').grid(row=3)
Label(master, text='Rental Company Info ').grid(row=4) 
Label(master,text='Company:').grid(row=5)
Label(master, text='Representatives:').grid(row=6)
Label(master, text='Location:').grid(row=7)
Label(master, text='City State/ZIP:').grid(row=8)
Label(master,text='Phone:').grid(row=9)
Label(master, text='Lessee Info ').grid(row=4,column=2)
Label(master,text='Name:').grid(row=5,column=2)
Label(master, text='License #:   ').grid(row=6,column=2)
Label(master,text='Address:').grid(row=7,column=2)
Label(master, text='City/state/ZIP:').grid(column=2,row=8)
Label(master, text='Phone: ').grid(column=2,row=9)
Label(master,text='VEHICLE INFORMATION').grid(row=10,column=2)
Label(master, text='VIN: ').grid(row=11)
Label(master,text='Make:').grid(row=12)
Label(master, text='Year:').grid(row=13)
Label(master, text='Color:').grid(row=14)
Label(master, text='Registration #').grid(row=11,column=2)
Label(master,text='Model:').grid(row=12,column=2)
Label(master, text='Mileage:').grid(row=13,column=2)
Label(master, text='VIN').grid(row=15,column=0)
Label(master, text='Cost/Day').grid(row=15,column=1)
Label(master, text='# ofDays').grid(row=15,column=2)
Label(master, text='Aditional Costs').grid(row=15,column=3)
Label(master, text='Line Total').grid(row=15,column=4)

Label(master, text='Subtotal:').grid(row=19,column=3) 
Label(master, text='Tax{%}:').grid(row=20,column=3)
Label(master, text='Total:').grid(row=21,column=3)
Label(master, text='Amount Paid:').grid(row=22,column=3)
Label(master, text='Payment Method:').grid(row=19,column=0)
Label(master,text='Authorized Signature:').grid(row=25,column=3)
Label(master,text='Representative Name:').grid(row=26,column=3)
e1 = Entry(master).grid(row=2,column=1)
e12=Entry(master).grid(row=3,column=1)
e2 =Entry(master).grid(row=5,column=1)
e3 =Entry(master).grid(row=6,column=1)
e4 =Entry(master).grid(row=7,column=1)
e5 =Entry(master).grid(row=8,column=1)
e6 =Entry(master).grid(row=9,column=1)
e7=Entry(master).grid(row=5,column=3)
e8=Entry(master).grid(row=6,column=3)
e9=Entry(master).grid(row=7,column=3)
e10=Entry(master).grid(row=8,column=3)
e11=Entry(master).grid(row=9,column=3)
e12=Entry(master).grid(row=11,column=1)
e13=Entry(master).grid(row=12,column=1)
e14=Entry(master).grid(row=13,column=1)
e15=Entry(master).grid(row=14,column=1)
e16=Entry(master).grid(row=11,column=3)
e17=Entry(master).grid(row=12,column=3)
e18=Entry(master).grid(row=13,column=3)
e19=Entry(master).grid(row=16,column=0) 
e20=Entry(master).grid(row=16,column=1)
e21=Entry(master).grid(row=16,column=2)
e22=Entry(master).grid(row=16,column=3)
e23=Entry(master).grid(row=16,column=4)
e24=Entry(master).grid(row=17,column=0)
e25=Entry(master).grid(row=17,column=1)
e26=Entry(master).grid(row=17,column=2)
e27=Entry(master).grid(row=17,column=3)
e28=Entry(master).grid(row=17,column=4)
e29=Entry(master).grid(row=18,column=0)
e30=Entry(master).grid(row=18,column=1)
e31=Entry(master).grid(row=18,column=2)
e32=Entry(master).grid(row=18,column=3)
e33=Entry(master).grid(row=18,column=4)
e34=Entry(master).grid(row=19,column=4)
e35=Entry(master).grid(row=20,column=4)
e36=Entry(master).grid(row=21,column=4)
e37=Entry(master).grid(row=22,column=4)
e38=Entry(master).grid(row=20,column=2)
e39=Entry(master).grid(row=21,column=1)
e40=Entry(master).grid(row=22,column=1)
e41=Entry(master).grid(row=25,column=4)
e42=Entry(master).grid(row=26,column=4)
var3 = IntVar()
Checkbutton(master, text="Cash:",variable=var3).grid(row=20, column=0)
var4 = IntVar() 
Checkbutton(master, text="Check No:",variable=var4).grid(row=20, column=1)
var5 = IntVar()
Checkbutton(master, text="Credit No:",variable=var5).grid(row=21, column=0)
var6 = IntVar()
Checkbutton(master, text="Other:",variable=var6).grid(row=22, column=0)
master.mainloop()
